name: catilda-landing
region: sfo
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
domains:
- domain: catilda.com
  type: PRIMARY
- domain: www.catilda.com
  type: ALIAS
static_sites:
- name: web
  environment_slug: html
  github:
    repo: yevhenkorotysh/catilda-landing
    branch: main
    deploy_on_push: true
  source_dir: /
  index_document: index.html
